"""update_models

Revision ID: b398182c07ac
Revises: c7ab89eabc6f
Create Date: 2026-04-22 15:40:13.261212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b398182c07ac'
down_revision: Union[str, Sequence[str], None] = 'c7ab89eabc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('title', sa.String(), nullable=False))
    op.alter_column('track_contributors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track_stats', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.add_column('tracks', sa.Column('lyrics', sa.String(), nullable=False))
    op.drop_column('tracks', 'lirics')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tracks', sa.Column('lirics', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tracks', 'lyrics')
    op.alter_column('track_stats', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('track_contributors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('releases', 'title')
    # ### end Alembic commands ###
